# -*- coding: utf-8 -*-
"""Exercícios While - Entregar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AGcDRCzaR_rlqG3cQuV7N0VNliZnkMpq

1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido.
"""

# E = tudo errado se nao for tudo verdade. Todas as condicoes precisam ser verdade
# Ou = Apenas uma das condicoes precisam ser valida

notadocliente = float(input("Digite uma nota apenas de 0 a 10: "))

while (notadocliente < 0) or (notadocliente > 10):
  print("nota invalida")
  notadocliente = float(input("Valor invalido! Informe novamente a nota, com numeros de 0 a 10 "))

print("nota valida")

"""2. Faça um programa que calcule e mostre a média aritmética de N notas."""

# Faça um programa que calcule a média aritmética de N notas
# Faça um programa que mostre a média aritmética de N notas
# N notas == Infinitas notas

notas = 0
N = int(input("Quantas notas serao digitadas para media?: "))
contador = 0 # contar a quantidade de notas
continuar == "S"

while continuar == "S"
  nota = int(input("Digite uma nota"))
  notas += nota
  contador += 1  # contador = contador + 1
  continuar = input ("Deseja continuar? Sim(S) ou qualquer tecla para sair")
print(f"A media das notas e: {notas\N:.f} ")

"""3. Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.
"""

# Faça um programa que leia um nome de usuário
# Faça um programa que leia a senha do usuário
# não aceite a senha igual ao nome do usuário
# mostrando uma mensagem de erro
# voltando a pedir as informações

nome = input("Digite o seu nome de usuario ")
senha = input("Digite uma senha: ")

while nome == senha:
  print(f" informacao errada! a senha nao pode ser igual ao nome do usuario! ")
  nome = input("Digite o seu nome de usuario ")
  senha = input("digite uma senha: ")

print(f"senha aprovada ")

"""4. Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.

"""

# recebe aumento salario anualmente
  # -> foi contratado em 1995
  # -> salario inicial de 1.000
  # -> em 1996 recebeu 1,5% sobre os 1000
  # -> 1997 (inclusive) dobro do ano anterior de 1,5% vai para 3% depois 6%
# Permitir que o usuario digite o salario atual ? Em 2024
#salario = 1
#aumento = 0.5
#salario = salario + aumento * salario
#print(salario)

salario = float(input("Digite o salário inicial do funcionário em 1995: "))
ano = 1995
ano_atual = int(input("Digite em que ano estamos: "))
aumento = 1.5/100

while ano < ano_atual:
  ano += 1
  salario *= 1 + aumento
  aumento *= 2
  print(f"O salario em {ano} é de R${salario:.2f} ")

"""5. Faça um programa que leia e valide as seguintes informações:
 Nome: maior que 3 caracteres;
 Idade: entre 0 e 150;
 Salário: maior que zero;
 Sexo: 'f' ou 'm';
 Estado Civil: 's', 'c', 'v', 'd';
"""

# Ler
# Validar
# Nome: input maior que 3 cacteres;
# Idade: int entre 0 e 150;
# Salario Maior quezero;
# Sexo: "f" ou "m"
# EStado civil: "s", "c", "v", "d";

nome = input("Digite seu nome completo: ")
idade = int(input("Digite a sua idade: "))
salario = float(input("Digite o seu salario: "))
sexo = input("Digite o seu sexo {f, m}: ")
estado_civil = input("Digite seu estado civil [s = solteiro; c = casado; [v = viuvo]; d = [divorciado]")

while len(nome) <= 3:
  nome = input("O nome precisa ter mais de 3 caracteres, digite seu nome: ")

while idade < 0 or idade > 150:
   idade = int(input("Idade invalida, Digite novamente sua idade: "))

while salario <= 0:
  salario = float(input("Seu pobre! Tenha mais que 0 na sua conta, digite novamente: "))

while sexo != "f" and != "m":
  sexo = input("Opcao invalida!, Digite o seu sexo novamente {f, m}: ")

while estado_civil = s, c, v, d:
  estado_civil = input("Entrada invalida! Digite o seu estado civil novamente [s, c, v, d]"):

"""6. Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

# país A seja da ordem de 80000
# taxa anual de crescimento de 3%
#

#calcule o numero de anos
#escreva o numero de anos
#manter as taxas de crescimento

paisA = 80.000
paisB = 200.000
ano = 0
while paisB >= paisA:
  paisA += paisA * 0.03
  paisB += paisB * 0.15

print(f"A quantidade de anos e: {ano} ")

"""7. Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120

"""

# calcular
# mostrar

numero = int(input("Digite o numero interiro para saber o fatorial: "))
contador = 1
fatorial = 1

while contador <= numero:
  fatorial = fatorial * contador
  contador += 1
print(fatorial)

"""8. Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados.
"""

# solicite ao usuário números indefinidamente até que ele digite 0
# calcular a media dos numeros digitados
# apresentar a media dos numeros digitados

soma = 0
quantidade = 0

while True:
  numero = float(input("Digite um numero qualquer ou 0 para sair: "))
  if numero == 0: # interrompe o loop com 0
    break

  soma += numero
  quantidade += 1

if quantidade > 0:
  media = soma/quantidade
  print(f"A media dos numeros digitados e {media} ")

else:
  print("nenhum numero foi digitado ")

"""9. A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um
programa capaz de gerar a série até o n−ésimo termo.
"""

ultimo = 1
penultimo = 1
cont = 1
print(ultimo)
print(penultimo)

while cont <= 9:
  termo = ultimo + penultimo
  penultimo = ultimo
  ultimo = termo
  cont += 1
  print(termo)

"""10-  O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e
agora possui uma loja de conveniências. Faça um programa que implemente uma
caixa registradora rudimentar.
 O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.
 O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra.
 A saída deve ser conforme o exemplo abaixo:
 Lojas Tabajara
 Produto 1: R$ 2.20
 Produto 2: R$ 5.80
 Produto 3: R$ 0
 Total: R$ 9.00
 Dinheiro: R$ 20.00
 Troco: R$ 11.00

"""

#  O programa deverá receber um número desconhecido de valores  aos preços das mercadorias
# Um valor zero deve ser informado pelo operador para indicar o final da compra.
# O programa deve então mostrar o total da compra e perguntar o valor em dinheiro que o cliente forneceu
# calcular e mostrar o valor do troco
# apos esta operacao, o programa devra voltar ao ponto inicial
# para registrar a proxima compra

print("Lojas Tabajaras")
total = 0
produto = 0
valor = 0

while True:
  total = 0
  produto += 1
  valor = float(input(f"produto {produto}: R$ "))
  if  valor == 0:
      break
  total += valor

print(f"O total da compra foi R${total:.2f} ")
dinheiro = float(input("dinheiro recebido: R$ "))
print(f"troco: {dinheiro - total:.2f} ")

"""11. O cardápio de uma lanchonete é o seguinte:
Especificação Código Preço
 Cachorro Quente 100 R$ 1,20
 Bauru Simples 101 R$ 1,30
 Bauru com ovo 102 R$ 1,50
 Hambúrguer 103 R$ 1,20
 Cheeseburguer 104 R$ 1,30
 Refrigerante 105 R$ 1,00
Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.
Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

# leia o código dos itens pedidos
# leia as quantidades desejadas
# Mostre o valor a ser pago por item
# Calcule o valor a ser geral do pedido
# Mostre o valor a ser geral do pedido
# Considere que o cliente deve informar quando o pedido deve ser encerrado

quantidade_produto_100 = 0
quantidade_produto_101 = 0
quantidade_produto_102 = 0
quantidade_produto_103 = 0
quantidade_produto_104 = 0
quantidade_produto_105 = 0
total = 0

print(
    "Produto                Código           Preço"
    "\n___________________________________________"
    "\nCachorro Quente      100            R$ 1.20"
    "\nBauru Simples        101            R$ 1.30"
    "\nBauru com Ovo        102            R$ 1.50"
    "\nHamburguer           103            R$ 1.20"
    "\nCheeseburguer        104            R$ 1.30"
    "\nRefrigerante         105            R$ 1.00\n"
)

while True:
  codigo = int(input("Digite o código do produto ou 0 para sair: "))
  if codigo == 0:
    break

  if codigo > 105 or codigo < 100:
    print("Código inválido! ")

    quantidade = int(input("Digite a quantidade desse produto ? "))

  if codigo == 100:
      quantidade_produto_100 += quantidade

  elif codigo == 101:
    quantidade_produto_101 += quantidade

  elif codigo == 102:
    quantidade_produto_102 += quantidade

  elif codigo == 103:
    quantidade_produto_103 += quantidade

  elif codigo == 104:
    quantidade_produto_104 += quantidade

  elif codigo == 105:
    quantidade_produto_105 += quantidade

print("\nFechamento do pedido"
      "\nCódigo - Quantidade - Preço unidade - Preço Total")

if quantidade_produto_100 > 0:
  print(f"100\t-\t{quantidade_produto_100}\t- R$ 1.20\t-"
        f"\tR$ {quantidade_produto_100 * 1.2:.2f} ")

  total += quantidade_produto_100 * 1.2
if quantidade_produto_101 > 0:
  print(f"101\t-\t{quantidade_produto_101}\t- R$ 1.30\t-"
        f"\tR$ {quantidade_produto_101 * 1.3:.2f} ")

total += quantidade_produto_101 * 1.3
if quantidade_produto_102 > 0:
  print(f"102\t-\t{quantidade_produto_102}\t- R$ 1.50\t-"
        f"\tR$ {quantidade_produto_102 * 1.5:.2f}" )

total += quantidade_produto_102 * 1.5
if quantidade_produto_103 > 0:
  print(f"103\t-\t{quantidade_produto_103}\t- R$ 1.20\t-"
        f"\tR$ {quantidade_produto_103 * 1.2:.2f} ")

total += quantidade_produto_103 * 1.2
if quantidade_produto_104 > 0:
  print(f"104\t-\t{quantidade_produto_104}\t- R$ 1.30\t-"
        f"\tR$ {quantidade_produto_104 * 1.3:.2f}" )

total += quantidade_produto_104 * 1.3
if quantidade_produto_105 > 0:
  print(f"105\t-\t{quantidade_produto_105}\t- R$ 1.00\t-"
        f"\tR$ {quantidade_produto_105 * 1.0:.2f}" )

total += quantidade_produto_105 * 1.0
print(f"Total do pedido: R$ {total:.2f}" )

"""12. Em uma eleição presidencial existem quatro candidatos. Os votos são informados
por meio de código.
Os códigos utilizados são:
 1, 2, 3, 4 - Votos para os respectivos candidatos
 (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
 5 - Voto Nulo
 6 - Voto em Branco
Faça um programa que calcule e mostre:
 O total de votos para cada candidato;
 O total de votos nulos;
 O total de votos em branco;
 A percentagem de votos nulos sobre o total de votos;
 A percentagem de votos em branco sobre o total de votos.
Para finalizar o conjunto de votos tem-se o valor zero.
"""

# apresentar candidatos
# informar o nulo, sair (0) e branco
# calcule e mostre
# O total de votos para cada candidato;
# O total de votos nulos;
# O total de votos em branco;
# A percentagem de votos nulos sobre o total de votos;
# percentagem de votos em branco sobre o total de votos.

print("Candidatos: \n1 - José\n2 - João\n3 - Maria\n4 - Clara ")
print("Digite 0 para sair, 5 para votar nulo ou 6 para votar ")
votos = 0
candidato_1 = 0
candidato_2 = 0
candidato_3 = 0
candidato_4 = 0
nulos = 0
brancos = 0

while True:
  voto = int(input(f"Digite o voto numero {votos + 1}: "))
if voto == 0:
      break

votos += 1
if voto == 1:
  candidato_1 += 1

elif voto == 2:
  candidato_2 += 1

elif voto == 3:
  candidato_3 += 1

elif voto == 4:candidato_4 += 1

elif voto == 5:
  nulos += 1

elif voto == 6:
  brancos += 1

else:
  print("Voto inválido!")
votos -= 1
print("\nResultado da eleição:"
      f"\nJosé teve {candidato_1} votos"
      f"\nJoão teve {candidato_2} votos"
      f"\nMaria teve {candidato_3} votos"
      f"\nClara teve {candidato_4} votos"
      f"\n{nulos} votos foram anulados, um total de {100 * nulo
      f"\n{brancos} votos foram em branco, "
      f"um total de {100 * brancos / votos:.2f}% ")